# Python project, check against all supported things.
language: python
matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
    - os: osx
      osx_image: xcode11
      language: shell
      before_install:
      - brew update -q
      - brew outdated python || brew upgrade python

# disable submodules from git
git:
  submodules: false
# commands to install dependencies
install:
  - "if [ -x "$(command -v apt-get)" ] && sudo apt-get install scons chrpath"
  # This will install PyLint but not where it does not work. It will fail
  # to install 2.6 and be buggy for 3.3
  - "pip install -r requirements-devel.txt"
  - "pip install ."
# commands to run tests
script:
  - ./tests/run-tests --no-other-python --skip-reflection-test --skip-all-cpython-tests
  - ./bin/check-nuitka-with-pylint --not-installed-is-no-error
